apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-reviewer
rules:
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: token-reviewer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: token-reviewer
subjects:
- kind: ServiceAccount
  name: db-server-service-account
  namespace: default

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-server-service-account
  namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: db-server-service-account-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: db-server-service-account
type: kubernetes.io/service-account-token