apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset
spec:
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq-service
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:alpine
        imagePullPolicy: "Always"
        envFrom:
          - secretRef:
              name: rabbitmq-secrets
        env:
          - name: RABBITMQ_DEFAULT_USER
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-config
                key: RABBITMQ_DEFAULT_USER
        ports:
          - containerPort: 5672
        volumeMounts:
          - name: rabbitmq-data
            mountPath: /var/lib/rabbitmq/
        resources:
          limits:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "200Mi"
          requests:
            cpu: "250m"
            memory: "512Mi"
            ephemeral-storage: "200Mi"
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
    - name: internal
      protocol: TCP
      port: 5672
      targetPort: 5672

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  resources:
    requests:
      storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
