# This workflow builds the docker images and pushes them to GHCR.
name: Build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - microservice: ./database
            image: ghcr.io/hyperclaw79/db_server
          - microservice: ./ingestion
            image: ghcr.io/hyperclaw79/ingestion
    steps:
      - name : Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Images
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.microservice }}
          push: true
          tags: |
            ${{ matrix.image }}
            ${{ matrix.image }}:latest