# This workflow will install Python dependencies and run linting.

name: Linting (Frontend)

on:
    push:
        paths:
            - frontend/**
            - .github/workflows/frontend-linting.yml
    pull_request:
        paths:
            - frontend/**
            - .github/workflows/frontend-linting.yml
    workflow_dispatch:

jobs:
    Linting_Frontend:
        strategy:
            matrix:
                node-version: [19.0.1]
            fail-fast: false
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  check-latest: true
            - name: Install dependencies (Frontend)
              run: |
                  npm install
            - name: Linting (Frontend)
              run: |
                  npm run lint
