# This workflow will install Python dependencies and run linting.

name: Linting

on:
  push:
    paths:
      - analysis/**.py
      - database/**.py
      - ingestion/**.py
  workflow_dispatch:

jobs:
  Linting:
    strategy:
      matrix:
        python-version: [3.11]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f dev_requirements.txt ]; then pip install -r dev_requirements.txt; fi
      - name: Linting
        run: |
          pylint -f colorized analysis database ingestion
